### PR TITLE
Fixes issue #32 for Exercise 15

### LINKED ISSUE #32: Exercise 15 - Statics Part 1
### Create a program that:

- Has an `Actor` class which has:
  - a `name` attribute
  - a `static` factory method for creating random actors which takes a random name from a list of actors and constructs them. You'll have to create this list internally in `Actor`. Make it a list of 20 possible names.
  - has a `private` constructor so that the only way to get an actor is to invoke the static factory method. This constructor enforces the requirement that an `Actor` must have a name set upon construction.

From your `Main` class, use the factory method to create a random `Actor` and display their name.

Note: This program has no user input so it doesn't require the use of `MenuHelper`

Here is a sample output:

```
I am Arnold Schwarzenegger!
```

### PR DESCRIPTION
**Pull request by nayema**
Fixes #32 - Generates random actor name using static variable and method.

### CODE REVIEW

File: exercise-15/src/com/nayema/Actor.java [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package com.nayema;
+
+public class Actor {
+    private static String[] name = {"Arnold Schwarzenegger", "Will Smith", "Anglenia Jolie", "Brad Pitt"};
+
+    private Actor() {
```
Comment (snasirca) [inline exercise-15/src/com/nayema/Actor.java]: - The private constructor was not used by a factory method to create an Actor.
- The Actor private constructor did not enforce the requirement that all Actors must have a name set at the start when they are initialized.

File: exercise-15/src/com/nayema/Actor.java [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+    }
+
+    public static void randomActorName() {
```
Comment (snasirca) [inline exercise-15/src/com/nayema/Actor.java]: Its fine to use a helper method that generates a random name. However this is not a factory method. It does not create an instantiated `Actor`.

File: exercise-15/src/com/nayema/Actor.java [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+        int length = name.length;
+        int random = (int)(Math.random() * length);
+        String actorName = name[random];
+        System.out.println(" I am " + actorName + "!");
```
Comment (snasirca) [inline exercise-15/src/com/nayema/Actor.java]: This method is doing too many things. Presentation concerns like this should be in `Main` for now as per the Issue instructions.

File: exercise-15/src/com/nayema/Main.java [hunk 4]
```diff
@@ -0,0 +1,8 @@
+package com.nayema;
+
+public class Main {
+
+    public static void main(String[] args) {
+        Actor.randomActorName();
```
Comment (snasirca) [inline exercise-15/src/com/nayema/Main.java]: Where is the invocation of the factory method on `Actor`? Why isn't the name of that instantiated object written out here using an `sout`?

**Review by snasirca — CHANGES_REQUESTED** [review]

**Review by snasirca — APPROVED** [review]
