### PR TITLE
Fixes issue #34 for Exercise 16

### LINKED ISSUE #34: Exercise 16 - Encapsulation Part 1 & Command Line Arguments
### Create a program that:

- Has a `Statistics` class which given an array of numbers can calculate a report containing:
  - the `mean`
  - the `median`
  - the `mode`
  - the `standard deviation`
  - the `variance`
- Use command line arguments to pass in a list of numbers.
- The `Statistics` class has an instance method called `setData` which takes an array of decimal point numbers (given via command line arguments) and saves them inside the `Statistics` class. The data is stored internally in `Statistics` such that it is *encapsulated* from the outside world. Only the `Statistics` class can access this stored information to perform its statistical calculations.
  - `setData` will also throw an `InvalidNumberException` if the user provides any command line arguments that are not a valid number.

Here are some sample usages:

```
> java -classpath out/production/exercise-16 com.nayema.Main 5 6.0 7 8 9
Statistics of the given data set:
Mean: 7
Median: 7
Mode: No mode for this data set
Std. Dev.: 1.5811388300842
Var: 2.5
```

```
> java -classpath out/production/exercise-16 com.nayema.Main 1 2 3 asdfJKL
Error: asdfJKL is not a valid number!
```

Bonus: What would happen if we were to change the implementation of `Statistics` and have it store the given data in a database prior to calculating?

### PR DESCRIPTION
**Pull request by nayema**
Fixes #34

### CODE REVIEW

File: exercise-16/src/com/nayema/Main.java [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package com.nayema;
+
+public class Main {
+
+    public static void main(String[] args) {
+        Statistics stats = new Statistics();
+
+        for (int i = 0; i < args.length; i++) {
```
Comment (snasirca) [inline exercise-16/src/com/nayema/Main.java]: Remove unnecessary `for` loop here

File: exercise-16/src/com/nayema/Main.java [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+            try {
+                stats.setData(args);
+            } catch (InvalidNumberException e) {
+                e.printStackTrace();
```
Comment (snasirca) [inline exercise-16/src/com/nayema/Main.java]: Print out the `errorMessage` attribute of the exception instance `e`

**Review by snasirca — CHANGES_REQUESTED** [review]
