### PR TITLE
Fixes OOP issue #21

### LINKED ISSUE #21: Exercise 10 - OOP Part 3
### Create a program that:

- Has a `Product` class with the following:
  - `price` attribute which is a decimal number
  - `taxAmount` method that returns the tax amount calculated which is _15%_ of the `price` of the `Product`

You're going to ask the user two questions and gather their input:
- What is the product name?
- What is the product price?

Once you have this information, you'll print out the name of the product and its price with the tax amount next to it like so:

```
What is the product name?
Fidget Spinner
What is the price in dollars?
10
The Fidget Spinner costs a total of $11.50
```

**Bonus:** Try to see if you can format the `price` as a two decimal places number so that it looks like a proper currency value.

### PR DESCRIPTION
**Pull request by nayema**
Fixes #21.

### CODE REVIEW

File: exercise-10/src/com/nayema/Main.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+import java.text.DecimalFormat;
+import java.util.Scanner;
+
+public class Main {
+
+    public static void main(String[] args) {
+        Scanner userInput = new Scanner(System.in);
+
+        System.out.println("What is the product name?");
+        String productName = userInput.nextLine();
```
Comment (snasirca) [inline exercise-10/src/com/nayema/Main.java]: Bring the `productName` into the `Product` class.

File: exercise-10/src/com/nayema/Product.java [hunk 2]
```diff
@@ -0,0 +1,14 @@
+package com.nayema;
+
+import java.util.Scanner;
+
+public class Product {
+    double price;
+    final double tax = 1.15; //15% sales tax
```
Comment (snasirca) [inline exercise-10/src/com/nayema/Product.java]: Uppercase the constant name to signal that this is a constant.

File: exercise-10/src/com/nayema/Product.java [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+
+    public void taxAmount() {
```
Comment (snasirca) [inline exercise-10/src/com/nayema/Product.java]: - Pull out the setting of `price` to `Main`.
- This method should be returning the calculated taxed amount. Not setting the `price` on the `Product`.

**Review by snasirca — CHANGES_REQUESTED** [review]

**Review by snasirca — APPROVED** [review]
