### PR TITLE
Fixes issue #30 for Exercise-14

### LINKED ISSUE #30: Exercise 14 - Polymorphism Part 1
### Create a program that:

- Has an abstract concept called `Vehicle` with the following method:
  - `getNumberOfWheels`
- Has these types of vehicles:
  - `Car`
  - `Bike`
  - `Tricycle`
  - `Truck`
- In `Main`, create an `ArrayList` of type `Vehicle` and add a few *Cars* and *Trucks*
- Iterate through the `ArrayList` and print out the number of wheels on each of the vehicles

Note: This program has no user input so it doesn't require the use of `MenuHelper`

Here is a sample output:

```
A Car has 4 wheels.
A Truck has 18 wheels.
A Bike has 2 wheels.
A Tricycle has 3 wheels.
```

Bonus: What happens if we were to add a `Boat` to our hierarchy of *Vehicles*? Does our abstraction still hold? Why or why not?

### PR DESCRIPTION
**Pull request by nayema**
Fixes #30.

A Boat class can not extend _Vehicle_ since it does not contain any number of wheels, therefore this abstract method cannot be implemented in Boat.

I would create an additional Abstract class called _Watercraft_. _Boat now can extend Watercraft.

### CODE REVIEW

File: exercise-14/src/com/nayema/Main.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+        ArrayList<Vehicle> vehicles = new ArrayList<>();
+        vehicles.add(car1);
+        vehicles.add(car2);
+        vehicles.add(car3);
+        vehicles.add(truck1);
+        vehicles.add(truck2);
+        vehicles.add(truck3);
+
+        for (int i = 0; i < vehicles.size(); i++) {
+            System.out.println("A " + vehicles.get(i).getClass().getSimpleName() + " has " + vehicles.get(i).getNumberOfWheels() + " wheels.");
```
Comment (snasirca) [inline exercise-14/src/com/nayema/Main.java]: Use the `Extract Variable` refactoring for the values being interpolated here.

**Review by snasirca — APPROVED** [review]
We paired to review the exercise. And introduced a `VehicleEntry` class.
